// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1xBGYGay0XZj0ow_J7qKPZXwJNljVYY',
    appId: '1:480566679152:web:edd430155db995ad3146b5',
    messagingSenderId: '480566679152',
    projectId: 'gemini-ai-d03e3',
    authDomain: 'gemini-ai-d03e3.firebaseapp.com',
    storageBucket: 'gemini-ai-d03e3.appspot.com',
    measurementId: 'G-513QEC9N6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50RLAw8ScnDBLwCLO691F0Yn9Uq8TKyA',
    appId: '1:480566679152:android:063e1257ab3db82c3146b5',
    messagingSenderId: '480566679152',
    projectId: 'gemini-ai-d03e3',
    storageBucket: 'gemini-ai-d03e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_C4joVu-C86xGWPQeq33O9Y6fTiW0gY',
    appId: '1:480566679152:ios:edd98ccf8ad4e66c3146b5',
    messagingSenderId: '480566679152',
    projectId: 'gemini-ai-d03e3',
    storageBucket: 'gemini-ai-d03e3.appspot.com',
    iosBundleId: 'com.example.advanceExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_C4joVu-C86xGWPQeq33O9Y6fTiW0gY',
    appId: '1:480566679152:ios:edd98ccf8ad4e66c3146b5',
    messagingSenderId: '480566679152',
    projectId: 'gemini-ai-d03e3',
    storageBucket: 'gemini-ai-d03e3.appspot.com',
    iosBundleId: 'com.example.advanceExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1xBGYGay0XZj0ow_J7qKPZXwJNljVYY',
    appId: '1:480566679152:web:e76c33f5f3c462283146b5',
    messagingSenderId: '480566679152',
    projectId: 'gemini-ai-d03e3',
    authDomain: 'gemini-ai-d03e3.firebaseapp.com',
    storageBucket: 'gemini-ai-d03e3.appspot.com',
    measurementId: 'G-C9LM08FPLZ',
  );
}
